### PR TITLE
features:barclamps need not run with base tests

### PR DESCRIPTION
**Pull request by mmnelemane**
changed feature:barclamps to features:barclamps as expected by rake.

### CODE REVIEW

**Comment by toabctl** [comment]
@mmnelemane I guess you wanted only the last commit, right?

**Comment by mmnelemane** [comment]
Yes.. only the last commit. just corrected now.

**Comment by toabctl** [comment]
+1

**Comment by vmoravec** [comment]
-1
The issue is rather typo in the name of the task, should be `features:barclamps`

**Comment by vmoravec** [comment]
+1 thanks for fix

**Comment by toabctl** [comment]
+1

**Pull request merged**
