### PR TITLE
Port tests for admin server on SLE12

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by vuntz** [comment]
I'm not sure when we want to merge this, or if we want to also allow things to stay working on SLE11?

**Comment by aspiers** [comment]
Surely it would be best to make it deal with both?  Aiming for an exact cutover will just cause misery.

**Comment by vuntz** [comment]
@aspiers actually, we're almost ready for an exact cutover ;-) But @vmoravec mentioned he will have a proper fix to allow the two versions.

**Comment by aspiers** [comment]
You might be ready, but I'm not ;-p

**Comment by vmoravec** [comment]
Superseded by https://github.com/SUSE-Cloud/cct/pull/14

**Pull request closed without merging**
