### PR TITLE
Add version constraints to gemspec

### PR DESCRIPTION
**Pull request by aspiers**
This is needed, because net-ssh 3.1.0beta1 onwards broke channels (or at least, in the way we use them with net-ssh-gateway).

(cherry picked from commit 6377be35c0322d9cd2f470f37a69391475f25c57)

### CODE REVIEW

**Comment by AbelNavarro** [comment]
+1

**Comment by aspiers** [comment]
This should fix https://trello.com/c/s9rAxq0j and unblock https://trello.com/c/3PR66srj

**Comment by aspiers** [comment]
@vmoravec Would be great if you could review this ASAP, since it's blocking completion of https://trello.com/c/3PR66srj which team Grapes been trying to complete for 4 sprints now :-)

**Comment by jsuchome** [comment]
+1 (but I've not tested it)

**Comment by vmoravec** [comment]
+1 if it solves the problem with the net-ssh channels. I addressed that problem by restricting their use in CI (if cct is run on admin node) in https://github.com/SUSE-Cloud/cct/pull/52, but the constraints are needed in gemspec anyway, thanks.

**Pull request merged**
