### PR TITLE
Revert "Add functional tests for nova client"

### PR DESCRIPTION
**Pull request by vmoravec**
Reverts SUSE-Cloud/cct#20

### CODE REVIEW

**Comment by vmoravec** [comment]
Error from jenkins: `rpm -q python-novaclient-test failed`
Seems like the test package/image is not available for some reason and `qa_crowbarsetup.sh` from automation needs to be fixed.

**Comment by vuntz** [comment]
Ah, I guess it's because the package is on the controller and cct is run on the admin server.

**Comment by vmoravec** [comment]
cct runs on the admin node, but it checks for package on the controller; some part of qa_crowbarsetup.sh code has not been run, jenkins job on qa hardware got it correctly however: https://ci.suse.de/job/cloud-mkphyscloud-qa/69/consoleFull . 

This code seems to be skiped on the recent jobs: https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L2579

**Comment by toabctl** [comment]
> This code seems to be skiped on the recent jobs: https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L2579

Nope. The code was executed and `python-novaclient-test` is installed. I think @vuntz is right. ~~`cct` executes the tests on the node where `cct` is running but it should be executed on the controller. So from https://github.com/SUSE-Cloud/cct/pull/20/files#diff-4c6d1e13a411da150ee6b1084b39f942R31 the code must run on the controller I think~~ . Seems that there is this `control_node.exec!()` method used...

**Pull request merged**
