### PR TITLE
check configfile extension to only load yml files

### PR DESCRIPTION
**Pull request by thutterer**
... otherwise .swp files from your editor get loaded too

### CODE REVIEW

**Comment by thutterer** [comment]
Should we also allow `.yaml` ?

**Comment by tboerger** [comment]
:+1:
`.yml` should be enough, we are not using `.yaml` anywhere.

**Comment by vmoravec** [comment]
Agree with @tboerger , and it's easier in the code to support a single extension.

Btw, I recommend you to set a single backup dir by `set backupdir=$HOME/.somedir` .
And we should maybe add `.swp` into `.gitignore` as well.

**Comment by tboerger** [comment]
> Btw, I recommend you to set a single backup dir by set backupdir=$HOME/.somedir .
> And we should maybe add .swp into .gitignore as well.

:+1:

**Comment by vmoravec** [comment]
:+1:

**Pull request merged**
