### PR TITLE
Backport changes from cloud 7

### PR DESCRIPTION
**Pull request by vmoravec**
Includes:
* upgrade
* other patches with enhancements

Tested on qa2 with cloud 6: https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-test-cct/113/console

### CODE REVIEW

**Comment by vmoravec** [comment]
[(5) #QA: Implement upgrade steps for landing page UI tests](https://trello.com/c/qD8vCEfA/199-5-qa-implement-upgrade-steps-for-landing-page-ui-tests)

**Review by jsuchome — COMMENTED** [review]
This is not very known to me, but the upgrade related part (check for landing page) looks correct.

**Comment by pgonin** [comment]
looks good to me

**Review by pgonin — APPROVED** [review]
ok for me

**Comment by gsanso** [comment]
Good work. Looks good to me.

**Review by jsuchome — APPROVED** [review]

**Pull request merged**
