### PR TITLE
Disable the test for admin server OS version

### PR DESCRIPTION
**Pull request by jsuchome**

### CODE REVIEW

**Comment by vmoravec** [comment]
+1

**Comment by sayalilunkad** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by jsuchome** [comment]
I expect the gating to fail here, because SP2 is still not used. But this is needed for https://github.com/SUSE-Cloud/automation/pull/1033

**Comment by jsuchome** [comment]
@vmoravec @sayalilunkad @toabctl I changed it significantly with last commit, do I still have your +1 ?

**Comment by vmoravec** [comment]
@jsuchome Please add a short FIXME note to make it clear why we won't run this test

**Comment by vmoravec** [comment]
Beside that it's still +1

**Comment by sayalilunkad** [comment]
+1

**Comment by toabctl** [comment]
~~@jsuchome I set the `do-not-merge-yet` label because this one depends on other PRs, right?~~

**Comment by jsuchome** [comment]
@toabctl no, this actually does not depend on anything, I disabled to test for admin OS

**Comment by toabctl** [comment]
+1 (test is disabled for now) so both, SP1 and SP2 can work

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
